// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

// This file is generated by running `flutter pub run build_runner build`
// in the project directory. This will generate the necessary adapters for Hive.

// After running the build_runner command, uncomment the following imports
// and use them to register your adapters in the main.dart file.

// import 'package:hive/hive.dart';
// import 'package:hive_flutter/hive_flutter.dart';
// import 'models/product.dart';
// import 'models/order.dart';
// import 'models/order_item.dart';

// Then add these lines in the main() function:
// await Hive.initFlutter();
// Hive.registerAdapter(ProductAdapter());
// Hive.registerAdapter(OrderAdapter());
// Hive.registerAdapter(OrderItemAdapter());
// await Hive.openBox<Product>('products');
// await Hive.openBox<Order>('orders');
